const news = [
  {
    id: 74845,
    title:
      "for the web3 devs: do you feel like working in this space has fucked up your mental health?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur6keq/for_the_web3_devs_do_you_feel_like_working_in/",
    created: "2022-05-16T21:28:34Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74844,
    title:
      "Zelensky addresses U.S. universities on rebuilding higher ed, bringing back students",
    url: "https://old.reddit.com/r/ukraine/comments/ur6kb3/zelensky_addresses_us_universities_on_rebuilding/",
    created: "2022-05-16T21:28:27Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74843,
    title:
      "Russia Lost A Third Of Its Forces In Ukraine. Now It’s Losing The War.",
    url: "https://old.reddit.com/r/ukraine/comments/ur6jrg/russia_lost_a_third_of_its_forces_in_ukraine_now/",
    created: "2022-05-16T21:27:44Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74842,
    title: "Are Russian propagandists waking up?",
    url: "https://old.reddit.com/r/ukraine/comments/ur6hok/are_russian_propagandists_waking_up/",
    created: "2022-05-16T21:25:07Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74841,
    title:
      "Putin making military decisions in Donbas - Western military source",
    url: "https://old.reddit.com/r/ukraine/comments/ur6crd/putin_making_military_decisions_in_donbas_western/",
    created: "2022-05-16T21:18:59Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74840,
    title: "XRP / Ripple: SEC Era of Corruption Will Soon Come to an End",
    url: "https://old.reddit.com/r/Ripple/comments/ur6bm5/xrp_ripple_sec_era_of_corruption_will_soon_come/",
    created: "2022-05-16T21:17:29Z",
    subChannel: "ripple",
    channel: "REDDIT",
  },
  {
    id: 74839,
    title:
      "I checked the sources of popular services and this is the only service of its kind that does not merge data))) guys in secret",
    url: "https://old.reddit.com/r/ukraine/comments/ur68sx/i_checked_the_sources_of_popular_services_and/",
    created: "2022-05-16T21:13:46Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74838,
    title:
      "What are you doing with your hard wallets? Is there anywhere to place your cold storage which insures it's value?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur66wa/what_are_you_doing_with_your_hard_wallets_is/",
    created: "2022-05-16T21:11:16Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74835,
    title: "Busses transport Azovstal fights to unknown location",
    url: "https://old.reddit.com/r/ukraine/comments/ur66qd/busses_transport_azovstal_fights_to_unknown/",
    created: "2022-05-16T21:11:03Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74836,
    title:
      "Ukrainian troops pinned down by Russian fire in key frontline village Izyum",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur66ou/ukrainian_troops_pinned_down_by_russian_fire_in/",
    created: "2022-05-16T21:11:00Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74837,
    title: "Fantom Stablecoin DEI Becomes Latest to Lose Dollar Peg",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur66kc/fantom_stablecoin_dei_becomes_latest_to_lose/",
    created: "2022-05-16T21:10:51Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74832,
    title:
      "Russia says agreement reached to evacuate wounded Ukrainian soldiers from Azovstal -- agencies",
    url: "https://old.reddit.com/r/ukraine/comments/ur64o7/russia_says_agreement_reached_to_evacuate_wounded/",
    created: "2022-05-16T21:08:38Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74834,
    title:
      "T-Mobile Sued for Security Lapses Over Cryptocurrency Costing Customer $750k",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur64ds/tmobile_sued_for_security_lapses_over/",
    created: "2022-05-16T21:08:15Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74833,
    title:
      "Video shows the 15th Territorial Defense Battalion “Bryanka-USSR” shelling Ukrainian Positions in Zolote May",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur640d/video_shows_the_15th_territorial_defense/",
    created: "2022-05-16T21:07:44Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74831,
    title: "I just want to congratulate you.",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur63lc/i_just_want_to_congratulate_you/",
    created: "2022-05-16T21:07:10Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74830,
    title: "Beautiful footage of Javelin in action",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur6136/beautiful_footage_of_javelin_in_action/",
    created: "2022-05-16T21:04:05Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74829,
    title: "BTC_proxy",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5zxq/btc_proxy/",
    created: "2022-05-16T21:02:41Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74826,
    title:
      "NFT Play to Earn projects you should keep an eye on in the current market",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5z88/nft_play_to_earn_projects_you_should_keep_an_eye/",
    created: "2022-05-16T21:01:47Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74827,
    title:
      "What are the most underrated crypto projects/coins who deserve way more love?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5z1p/what_are_the_most_underrated_crypto_projectscoins/",
    created: "2022-05-16T21:01:33Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74828,
    title:
      "Bond to Unbind - Documentary about Bitcoin and El Salvador telling local stories",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5yrf/bond_to_unbind_documentary_about_bitcoin_and_el/",
    created: "2022-05-16T21:01:13Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74824,
    title:
      "Ukrainian military destroy 178 enemy troops and five tanks in eastern Ukraine",
    url: "https://old.reddit.com/r/ukraine/comments/ur5yjz/ukrainian_military_destroy_178_enemy_troops_and/",
    created: "2022-05-16T21:00:59Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74825,
    title:
      "Northern Saltivka, Kharkiv, Ukraine. Consequences of shelling by Russian troops",
    url: "https://old.reddit.com/r/ukraine/comments/ur5y0l/northern_saltivka_kharkiv_ukraine_consequences_of/",
    created: "2022-05-16T21:00:20Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74822,
    title: "Anyone want to donate lol 😂 🥹",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5ps0/anyone_want_to_donate_lol/",
    created: "2022-05-16T20:50:05Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74823,
    title:
      "Ukrainian artillery destroys a Russian ammunition depot along with trucks",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur5o8h/ukrainian_artillery_destroys_a_russian_ammunition/",
    created: "2022-05-16T20:48:10Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74821,
    title: "Feel free to donate lol 😂 🥹",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5o8o/feel_free_to_donate_lol/",
    created: "2022-05-16T20:48:10Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74820,
    title:
      "Popular news reporter is shot by the IDF and her rescuer is also shot",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur5mrw/popular_news_reporter_is_shot_by_the_idf_and_her/",
    created: "2022-05-16T20:46:23Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74819,
    title: "crypto.com is stealing deposits",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5ku4/cryptocom_is_stealing_deposits/",
    created: "2022-05-16T20:43:59Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74818,
    title: "My Small Business Now Accepts Crypto! 🥳",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5jxq/my_small_business_now_accepts_crypto/",
    created: "2022-05-16T20:42:48Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74817,
    title: "Stories of people who lived under russian occupation",
    url: "https://old.reddit.com/r/ukraine/comments/ur5h1n/stories_of_people_who_lived_under_russian/",
    created: "2022-05-16T20:39:14Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74816,
    title:
      "💔 Bus with the wounded taken out of the Azovstal plant, May 16. Photo: Alexander Yermochenko / Reuters",
    url: "https://old.reddit.com/r/ukraine/comments/ur5h06/bus_with_the_wounded_taken_out_of_the_azovstal/",
    created: "2022-05-16T20:39:11Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74814,
    title:
      "Ukraine forces destroyed a fairly rare Russian BMP-1AM infantry fighting vehicle in the East",
    url: "https://old.reddit.com/r/ukraine/comments/ur5fx1/ukraine_forces_destroyed_a_fairly_rare_russian/",
    created: "2022-05-16T20:37:50Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74815,
    title:
      "Ukraine has won the battle for Kharkiv but what is next for Zelenskyy’s army?, by Major-General Mick Ryan (retired), Australian Army. (A strategic window of opportunity is opening for Ukraine — and timing will be vital.)",
    url: "https://old.reddit.com/r/ukraine/comments/ur5fsi/ukraine_has_won_the_battle_for_kharkiv_but_what/",
    created: "2022-05-16T20:37:40Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74811,
    title: "Do Kwon wants to fork the Terra blockchain as part of revival plan",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5ctl/do_kwon_wants_to_fork_the_terra_blockchain_as/",
    created: "2022-05-16T20:33:58Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74812,
    title: "How to start mining?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5crr/how_to_start_mining/",
    created: "2022-05-16T20:33:54Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74813,
    title:
      "Running low on ammo, Green Berets of the United States Military manage to regroup with the convoy using overwhelming firepower. (Afghanistan, Date Unknown.)",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur5bro/running_low_on_ammo_green_berets_of_the_united/",
    created: "2022-05-16T20:32:38Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74810,
    title:
      "Two Russian BMP's drive headlong into a minefield, Ukrainian drone watches the results unfold",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur5a3n/two_russian_bmps_drive_headlong_into_a_minefield/",
    created: "2022-05-16T20:30:36Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74809,
    title:
      'Ukraine forces fire a U.S. 12.7mm Browning M2 "Ma Deuce" heavy machine gun from the cargo bed of a pickup truck',
    url: "https://old.reddit.com/r/ukraine/comments/ur5918/ukraine_forces_fire_a_us_127mm_browning_m2_ma/",
    created: "2022-05-16T20:29:24Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74807,
    title: "Check out this upcoming cryptocurrency",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur5740/check_out_this_upcoming_cryptocurrency/",
    created: "2022-05-16T20:27:00Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74808,
    title: "Swapnex Exit Scam? WITHDRAWAL PROBLEM ALERT WATCH THIS VIDEO",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur56lf/swapnex_exit_scam_withdrawal_problem_alert_watch/",
    created: "2022-05-16T20:26:20Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74806,
    title: "questions about 'buying into' crypto",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur55px/questions_about_buying_into_crypto/",
    created: "2022-05-16T20:25:14Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74803,
    title:
      "Russian losses explained: retired general says one-third of ground forces reduced",
    url: "https://old.reddit.com/r/ukraine/comments/ur4yfk/russian_losses_explained_retired_general_says/",
    created: "2022-05-16T20:16:06Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74804,
    title:
      "Binance's CZ lost $1.6 billion in Luna investment. Now the CEO is pushing to have retail users reimbursed before Binance.",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4y3y/binances_cz_lost_16_billion_in_luna_investment/",
    created: "2022-05-16T20:15:42Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74805,
    title:
      "Michael Saylor: \"The reason that Bitcoin is magical is because there's only 21 million. I can create more real estate in NYC. I can create more cars. I can create more luxury watches ... Bitcoin is a scarcity. Name another scarcity in the world ... It's not clear there is another scarcity.\"",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4xp8/michael_saylor_the_reason_that_bitcoin_is_magical/",
    created: "2022-05-16T20:15:12Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74801,
    title: "Russia’s Ka-52 Attack Helicopters Have A Serious Vibration Problem",
    url: "https://old.reddit.com/r/ukraine/comments/ur4w7g/russias_ka52_attack_helicopters_have_a_serious/",
    created: "2022-05-16T20:13:21Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74802,
    title:
      'W&R:SR "Help for Ukraine" DLC (Revenue will be Donating to the Ukrainian Red Cross)',
    url: "https://old.reddit.com/r/ukraine/comments/ur4w1h/wrsr_help_for_ukraine_dlc_revenue_will_be/",
    created: "2022-05-16T20:13:09Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74800,
    title: "We still hodling!!",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4v4v/we_still_hodling/",
    created: "2022-05-16T20:12:00Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74799,
    title:
      "Realm of the living. How fishermen of the Dreadful Forest saved 2,000 people from famine and Russian occupation",
    url: "https://old.reddit.com/r/ukraine/comments/ur4ung/realm_of_the_living_how_fishermen_of_the_dreadful/",
    created: "2022-05-16T20:11:23Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74798,
    title:
      "Body Cam Footage: Azov SSO Unit Fighting Within Grenade Range of the Russians in the Donetsk Region",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur4twq/body_cam_footage_azov_sso_unit_fighting_within/",
    created: "2022-05-16T20:10:25Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74797,
    title:
      "Russia could strike back at the West by calling on its network of white-supremacist groups to commit terror attacks there, analysts warn",
    url: "https://old.reddit.com/r/ukraine/comments/ur4ttn/russia_could_strike_back_at_the_west_by_calling/",
    created: "2022-05-16T20:10:18Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74796,
    title: "Invasion Day 82 – Summary - MilitaryLand.net",
    url: "https://old.reddit.com/r/ukraine/comments/ur4tb8/invasion_day_82_summary_militarylandnet/",
    created: "2022-05-16T20:09:42Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74795,
    title:
      'Card decks: "Covered card of Ruscism" and "War Criminals" projects by InformNapalm - InformNapalm.org (English)',
    url: "https://old.reddit.com/r/ukraine/comments/ur4s8j/card_decks_covered_card_of_ruscism_and_war/",
    created: "2022-05-16T20:08:26Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74794,
    title: "mans be surely gonna retire after that",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4r2m/mans_be_surely_gonna_retire_after_that/",
    created: "2022-05-16T20:07:02Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74792,
    title: "There’s more to life",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4p9p/theres_more_to_life/",
    created: "2022-05-16T20:04:53Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74793,
    title:
      'Kalush Orchestra returns to Ukraine after Eurovision win. The Ukrainian band gave an impromptu performance of the winning song, "Stefania," for the members of Ukraine\'s State Border Guard Service after crossing the border on their way home.',
    url: "https://old.reddit.com/r/ukraine/comments/ur4ozs/kalush_orchestra_returns_to_ukraine_after/",
    created: "2022-05-16T20:04:34Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74791,
    title: "Decentralisation brings High Risk",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4n7t/decentralisation_brings_high_risk/",
    created: "2022-05-16T20:02:28Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74789,
    title:
      "Aftermath of M777 Howitzer work: Ukraine forces destroyed a Russian weapon warehouse together with 7 × BMPs, a battle tank, and a company’s worth of soldiers earlier today. The site is obliterated.",
    url: "https://old.reddit.com/r/ukraine/comments/ur4n5k/aftermath_of_m777_howitzer_work_ukraine_forces/",
    created: "2022-05-16T20:02:24Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74790,
    title: "Fourth mass grave revealed through satellite imagery in Mariupol",
    url: "https://old.reddit.com/r/ukraine/comments/ur4n1y/fourth_mass_grave_revealed_through_satellite/",
    created: "2022-05-16T20:02:16Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74788,
    title:
      "Hungary ‘holding EU hostage’ over sanctions on Russian oil | Hungary",
    url: "https://old.reddit.com/r/ukraine/comments/ur4lms/hungary_holding_eu_hostage_over_sanctions_on/",
    created: "2022-05-16T20:00:36Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74787,
    title: "U.S. SEC chair says much to be done to protect crypto investors",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4kqs/us_sec_chair_says_much_to_be_done_to_protect/",
    created: "2022-05-16T19:59:41Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74785,
    title: "A facebook page for Ukrainian in Campania (Naples region)",
    url: "https://old.reddit.com/r/ukraine/comments/ur4k3t/a_facebook_page_for_ukrainian_in_campania_naples/",
    created: "2022-05-16T19:58:49Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74786,
    title: "So here's the war summed up neatly, so far",
    url: "https://old.reddit.com/r/ukraine/comments/ur4iui/so_heres_the_war_summed_up_neatly_so_far/",
    created: "2022-05-16T19:57:09Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74784,
    title: "Crushing",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur4hyg/crushing/",
    created: "2022-05-16T19:55:57Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74782,
    title:
      "LUNA will be forked: Legacy chain would be Terra Classic, and the newer chain - Terra. Newer chain would be without any algorithmic stablecoins. (This does absolutely nothing to the LUNA ecosystem.)",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4h5g/luna_will_be_forked_legacy_chain_would_be_terra/",
    created: "2022-05-16T19:54:57Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74783,
    title:
      "Stablecoins' untethering may prompt regulation: Fitch | Advisor's Edge",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4gzm/stablecoins_untethering_may_prompt_regulation/",
    created: "2022-05-16T19:54:45Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74781,
    title:
      "A sharpshooter from the Syrian army kills a Syrian rebel as he peers from a window. (2013, Syria)",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur4efq/a_sharpshooter_from_the_syrian_army_kills_a/",
    created: "2022-05-16T19:51:37Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74779,
    title:
      "Video of a Russian UAV dropping a grenade (RGD-5?) in a plastic cup on Ukrainian positions.",
    url: "https://old.reddit.com/r/ukraine/comments/ur4du0/video_of_a_russian_uav_dropping_a_grenade_rgd5_in/",
    created: "2022-05-16T19:50:52Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74780,
    title:
      "Islamic Front sniper appears to put an anti-materiel round through the engine of a bus carrying SAA soldiers - Damascus - 2014",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur4d6o/islamic_front_sniper_appears_to_put_an/",
    created: "2022-05-16T19:50:09Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74778,
    title:
      "Slingshot’s mobile app 🎉 Waitlist today + earn NFT and Bitcoin rewards.",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4ctz/slingshots_mobile_app_waitlist_today_earn_nft_and/",
    created: "2022-05-16T19:49:43Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74775,
    title:
      "Why 155mm shells that supplied by West for M777 is deadlier than the Russian made 152mm? Here's why. - Trent Telenko on Twitter",
    url: "https://old.reddit.com/r/ukraine/comments/ur4c6k/why_155mm_shells_that_supplied_by_west_for_m777/",
    created: "2022-05-16T19:48:55Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74774,
    title: "Russian artillery and ammunition",
    url: "https://old.reddit.com/r/ukraine/comments/ur4ayj/russian_artillery_and_ammunition/",
    created: "2022-05-16T19:47:24Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74773,
    title:
      "Correlation Between Crypto and Stocks Volatility Grows as Markets React to QT",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur4anv/correlation_between_crypto_and_stocks_volatility/",
    created: "2022-05-16T19:47:01Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74772,
    title:
      "A lot of Zelensky's speeches are fantastic but this one made my jaw drop",
    url: "https://old.reddit.com/r/ukraine/comments/ur4ae4/a_lot_of_zelenskys_speeches_are_fantastic_but/",
    created: "2022-05-16T19:46:42Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74771,
    title: "Blockchain ETFs Lead the Market Bounce",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur49sr/blockchain_etfs_lead_the_market_bounce/",
    created: "2022-05-16T19:45:55Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74770,
    title: "Starlink in the trenches on the front line",
    url: "https://old.reddit.com/r/ukraine/comments/ur48rn/starlink_in_the_trenches_on_the_front_line/",
    created: "2022-05-16T19:44:35Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74769,
    title: "Crypto storage: Cold, hot, or maybe a little of both?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur489j/crypto_storage_cold_hot_or_maybe_a_little_of_both/",
    created: "2022-05-16T19:43:54Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74768,
    title:
      "Toys seized by the italian financial police were handed over to Caritas Diocesana so as to be made available for donation to Ukrainian girls fleeing the war (in italian)",
    url: "https://old.reddit.com/r/ukraine/comments/ur47sh/toys_seized_by_the_italian_financial_police_were/",
    created: "2022-05-16T19:43:14Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74767,
    title:
      "Portugal’s Status as a Crypto Tax Haven Appears to Be Ending - Decrypt",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur47nf/portugals_status_as_a_crypto_tax_haven_appears_to/",
    created: "2022-05-16T19:43:03Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74765,
    title:
      "Big shock wave after (reportedly) drone-corrected Ukrainian artillery fire hits Russian self-propelled artillery [music by original video maker]",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur453z/big_shock_wave_after_reportedly_dronecorrected/",
    created: "2022-05-16T19:39:52Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74764,
    title: "A Global Energy Shortage Is Putting Bitcoin Under Pressure",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur43rr/a_global_energy_shortage_is_putting_bitcoin_under/",
    created: "2022-05-16T19:38:09Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74763,
    title:
      "A Ukrainian soldier proposes to his girlfriend in Kharkiv while onlookers rev their engines in support",
    url: "https://old.reddit.com/r/ukraine/comments/ur42fl/a_ukrainian_soldier_proposes_to_his_girlfriend_in/",
    created: "2022-05-16T19:36:25Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74762,
    title: "War in Manhattan 2022 [OC made by AI = Not real]",
    url: "https://old.reddit.com/r/CombatFootage/comments/ur41vc/war_in_manhattan_2022_oc_made_by_ai_not_real/",
    created: "2022-05-16T19:35:39Z",
    subChannel: "combatfootage",
    channel: "REDDIT",
  },
  {
    id: 74761,
    title:
      "Indian Regulator Makes it Harder for Celebrities And Influencers to Promote Crypto",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur413c/indian_regulator_makes_it_harder_for_celebrities/",
    created: "2022-05-16T19:34:43Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74760,
    title: "Buy a house in Canada with crypto!",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3zq8/buy_a_house_in_canada_with_crypto/",
    created: "2022-05-16T19:33:04Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74759,
    title:
      "Putin’s tables are a-changing, metamorphosing into “long and round,” mimicking his pathetic strategy in Ukraine-long salients getting encircled.",
    url: "https://old.reddit.com/r/ukraine/comments/ur3ywv/putins_tables_are_achanging_metamorphosing_into/",
    created: "2022-05-16T19:32:01Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74758,
    title:
      'Discussion: I posted a tweet from the Reuters US national security correspondent Idrees Ali, breaking news of the Azovstal fighters leaving the complex, and the Mods deleted it because it "originates from a non-credible source". Do we think this sub is well served by its mods?',
    url: "https://old.reddit.com/r/ukraine/comments/ur3xay/discussion_i_posted_a_tweet_from_the_reuters_us/",
    created: "2022-05-16T19:29:59Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74757,
    title: "Question about long/shorting",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3wev/question_about_longshorting/",
    created: "2022-05-16T19:28:47Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74766,
    title: "Looking forward to the Binance AMA - What's your questions?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3v4p/looking_forward_to_the_binance_ama_whats_your/",
    created: "2022-05-16T19:27:01Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74756,
    title: "Difference between Interledger Protocol and Overledger?",
    url: "https://old.reddit.com/r/Ripple/comments/ur3u5x/difference_between_interledger_protocol_and/",
    created: "2022-05-16T19:25:46Z",
    subChannel: "ripple",
    channel: "REDDIT",
  },
  {
    id: 74754,
    title:
      "Reuters: About a dozen buses carrying Ukrainian Azovstal servicemen leave plant",
    url: "https://old.reddit.com/r/ukraine/comments/ur3tqy/reuters_about_a_dozen_buses_carrying_ukrainian/",
    created: "2022-05-16T19:25:13Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74752,
    title: "Azovstal Situation Megathread",
    url: "https://old.reddit.com/r/ukraine/comments/ur3t9j/azovstal_situation_megathread/",
    created: "2022-05-16T19:24:34Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74753,
    title: "Israeli diplomats in Kyiv for first time since Russia invaded",
    url: "https://old.reddit.com/r/ukraine/comments/ur3syi/israeli_diplomats_in_kyiv_for_first_time_since/",
    created: "2022-05-16T19:24:12Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74751,
    title: "Chainlink Hires Google Vet Who Developed TensorFlow AI System",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3qsd/chainlink_hires_google_vet_who_developed/",
    created: "2022-05-16T19:21:18Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74750,
    title: "found a wallet from 2015..",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3pv1/found_a_wallet_from_2015/",
    created: "2022-05-16T19:20:08Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74749,
    title:
      "Everybody wonders who some of theses western intel groups are that providing critical data and deeply embedded only operative level intel. For those that don't know... I introduce to you the 4th Psychological Operations Group. Video may be unsettling for some.",
    url: "https://old.reddit.com/r/ukraine/comments/ur3pjw/everybody_wonders_who_some_of_theses_western/",
    created: "2022-05-16T19:19:45Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74748,
    title:
      "$3 billion in bitcoin was sold in a last-ditch attempt to save UST stablecoin from collapse",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3p2r/3_billion_in_bitcoin_was_sold_in_a_lastditch/",
    created: "2022-05-16T19:19:10Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74747,
    title: "Cryptocurrency and the Climate Crisis",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3nsu/cryptocurrency_and_the_climate_crisis/",
    created: "2022-05-16T19:17:29Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74777,
    title:
      "Can somebody explain what Do Kwons newest plan to save Luna actually looks like in practice?",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3nem/can_somebody_explain_what_do_kwons_newest_plan_to/",
    created: "2022-05-16T19:16:58Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74744,
    title:
      "About a dozen buses carrying Ukrainian Azovstal servicemen leave plant - Reuters witness",
    url: "https://old.reddit.com/r/ukraine/comments/ur3inm/about_a_dozen_buses_carrying_ukrainian_azovstal/",
    created: "2022-05-16T19:10:56Z",
    subChannel: "ukraine",
    channel: "REDDIT",
  },
  {
    id: 74745,
    title:
      "I have a lot of excitement for the metaverse! Anybody have any excitement about any particular project that you’d like to share??",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3ich/i_have_a_lot_of_excitement_for_the_metaverse/",
    created: "2022-05-16T19:10:34Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
  {
    id: 74746,
    title:
      "Bitcoin Gearing Up for a Big Move in the Next Three Months, Says Crypto Strategist – Here Are His Targets - The Daily Hodl",
    url: "https://old.reddit.com/r/CryptoCurrency/comments/ur3i1j/bitcoin_gearing_up_for_a_big_move_in_the_next/",
    created: "2022-05-16T19:10:12Z",
    subChannel: "cryptocurrency",
    channel: "REDDIT",
  },
];

function useNewsClient() {
  const loading = false;
  const loadMore = () => {};
  const subscribeSubreddits = () => {};
  const unsubscribeSubreddits = () => {};

  return {
    news,
    loading,
    loadMore,
    subscribeSubreddits,
    unsubscribeSubreddits,
  };
}

export default useNewsClient;
